### ISSUE TITLE
Unclear How to Use

### ISSUE THREAD

**Issue by Mastermind497** [google/postcss-rename#43]
I wanted to use this plugin with NextJS and tailwind, but there seems to be no guide on how to use it at all. Is there any tutorial I can follow?

**Comment by nex3** [comment]
There's not (yet) a batteries-included solution for using this package. It provides the ability to rewrite your CSS selectors, but in order to refer to the rewritten selectors you'll also need to rewrite your HTML or JS class names which will require another plugin working in concert with this one. That's outside the scope of this plugin, although once something like that exists we can document how to use both at once.
